### ISSUE TITLE
Cope

### ISSUE THREAD

**Issue by augustozanellato** [iTODDLERS-BTFO/iToddlers-BTFO#1]

**Comment by AlecsFerra** [comment]
@augustozanellato cope

**Comment by meow6969** [comment]
i like playing video games

**Comment by khanghugo** [comment]
cope

**Comment by gxfr** [comment]
sneed

**Comment by synchromach** [comment]
>cope
![1703673637090367](https://github.com/iTODDLERS-BTFO/iToddlers-BTFO/assets/154671247/374068b8-8aee-493c-9f58-08222e9bf589)
