### ISSUE TITLE
Add iPhones are allergic to helium

### ISSUE THREAD

**Issue by Zipdox** [iTODDLERS-BTFO/iToddlers-BTFO#2]
https://www.ifixit.com/News/11986/iphones-are-allergic-to-helium

**Comment by Zipdox** [comment]
![iphones allergic to helium](https://user-images.githubusercontent.com/42157341/154548812-986a717c-6655-43d4-aa7e-bcea5a24ca02.png)

**Comment by gxfr** [comment]
done
