### ISSUE TITLE
Airpods max additions

### ISSUE THREAD

**Issue by Zipdox** [iTODDLERS-BTFO/iToddlers-BTFO#4]
https://screenrant.com/apple-airpods-max-headphones-earcup-condensation/

https://www.macrumors.com/2022/10/25/airpods-max-anc-performance-reduced/

**Comment by gxfr** [comment]
if u take the screenshot i'll add it

**Comment by Zipdox** [comment]
![image](https://user-images.githubusercontent.com/42157341/205521439-3102c456-c8b0-4360-9887-ea7c080eb276.png)
![image](https://user-images.githubusercontent.com/42157341/205521485-18f9ddfd-75fc-43b5-a100-788562babfe9.png)
